title: Page Title
email: email@domain.xyz
description: >- # this means to ignore newlines until "baseurl:"
  A paragraph describing your webpage.
baseurl: "/blog" # the subpath of your site
url: "domain.xyz" # the base hostname & protocol for your site
twitter_username:
github_username:  

# Required plugins for the theme to work properly
plugins:
  - jekyll-remote-theme
  - jemoji

# Including jekyll-shell-theme using the jekyll-remote-theme plugin
remote_theme: tareqdandachi/jekyll-shell-theme

sass:
  style: compressed

highlighter: rouge #selecting the highlighter, default is rouge

header_pages:
  - index.md
  - about.md
  - a-third-page.md


font-size: small 
