#!/usr/bin/env bash

# Colors for output
text_blue="$(tput setaf 4)"
text_red="$(tput setaf 1)"
text_green="$(tput setaf 2)"
text_bold="$(tput bold)"
text_reset="$(tput sgr0)"
line=$(printf '=%.0s' $(seq 1 "$(tput cols)"))

# Display storage information
display_storage_info() {
    echo -e "${line}\n"
    echo -e "${text_blue}${text_bold}Storage Information:${text_reset}\n"
    df -h
    echo -e "${line}\n"
}

# Display webserver status
display_webserver_status() {
    echo -e "${text_blue}${text_bold}Webserver Status:${text_reset}"
    local webservers=("apache2" "httpd" "nginx")
    local found=0
    for service in "${webservers[@]}"; do
        if systemctl list-units --type=service | grep -q "$service.service"; then
            local status
            status=$(systemctl is-active "$service.service")
            if [[ "$status" == "active" ]]; then
                echo -e "${text_bold}$service.service${text_reset} is ${text_green}$status${text_reset}"
            else
                echo -e "${text_bold}$service.service${text_reset} is ${text_red}$status${text_reset}"
            fi
            found=1
        fi
    done
    if [[ "$found" -eq 0 ]]; then
        echo -e "${text_red}No webserver services are running.${text_reset}"
    fi
    echo -e "${line}\n"
}

# Main execution based on arguments
if [[ $# -lt 1 ]]; then
    echo -e "
Usage:
  homelab -webserver storage    # Display storage information.
  homelab -webserver status     # Display the status of webserver services (apache2, httpd, nginx).
  homelab -webserver all        # Display both webserver status and storage information.
  --help                        # Display this help message."
    exit 1
fi

option="$1"

case "$option" in
    status)
        display_webserver_status
        ;;
    storage)
        display_storage_info
        ;;
    all)
        display_storage_info
        display_webserver_status
        ;;
    --help)
        echo -e "
Usage:
  homelab -webserver storage    # Display storage information.
  homelab -webserver status     # Display the status of webserver services (apache2, httpd, nginx).
  homelab -webserver all        # Display both webserver status and storage information.
  --help                        # Display this help message."
        ;;
    *)
        echo -e "${text_red}Invalid option.${text_reset} Use --help to see the available options."
        ;;
esac
